### ISSUE TITLE
URL and organization name: COVID vs Clinical 

### ISSUE THREAD

**Issue by chrisroederucdenver** [National-Clinical-Cohort-Collaborative/guide-to-n3c-v1#248]
N3C still points to the COVID URL. I see it here as e [National COVID Cohort Collaborative](https://ncats.nih.gov/n3c) (N3C).

Also the first page still references the organization with COVID.

...and for closure, there's an issue on the site about this: https://unite.nih.gov/workspace/issues-app/issue/ri.issues.main.issue.3b9fc5b9-643a-4e0d-bb59-5ef520557728

**Comment by oneilsh** [comment]
Ok, I think I have the redirect setup via the new org with old name trick. New redirecting repo here: https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1

There are a number of broken in links in the Guide now though, I see a lot of references in the markdown to the old repo name: https://github.com/search?q=repo%3ANational-Clinical-Cohort-Collaborative%2Fguide-to-n3c-v1%20national-covid-cohort-collaborative&type=code @wibeasley , would this just require a rebuild from sources, or do we need to edit those by hand? Is there a way to have these built as relative links?

**Comment by wibeasley** [comment]
Sweet, thanks for doing that.  It works for me.

Regarding your question about the broken links:

1. I imagine updating the `repo-url` in [_quarto.yml](https://github.com/National-Clinical-Cohort-Collaborative/guide-to-n3c-v1/blob/main/_quarto.yml) will take care a lot that the reader encounters.  
2. Any hits in an html file can be ignored, as long as the source md/qmd files are fixed

Among those links that you have above, 

3. Some probably should be updated to be quarto relative cross-references
4. Most point to the repo itself, and not the book.  So they'll need to be updated (eg, `…s tracked via [issues](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/issues?q=is%3Aissue). Se…`)

I can probably do that this afternoon or weekend.  Unless you'd like to.

**Comment by wibeasley** [comment]
Closed with #250.  Please see #249 for a remaining limitation.
